---
- name: Fortinet Firewall
  hosts: localhost
  connection: local
#  hosts: fortinet
  gather_facts: true

  tasks:
  - name: Backup Fortigate Config
    include_role:
      name: backup_config
#      vars_from: "password.yml"
