- name: backup Fortigate
  connection: local
  hosts: fortinet
  
  tasks:
  - name: Backup Config
    fortios_config:
      host: "{{ansible_host}}"
      username: "{{user_name}}"
      password: "{{password_name}}"
      backup: yes
      backup_path: /backup/soc/
      backup_filename: fg_config.bak
