- name: fortigate config backup
#  connection: local
  hosts: localhost

  tasks:
    - name: get current config
      get_url:
#      uri:
        url: http://{{ ansible_host }}/api/v2/monitor/system/config/backup/?scope=global&access_token={{ access_token }}
#        return_content: yes
#        validate_certs: yes
        dest: /backup/soc/{{ inventory_hostname }}_{{ ansible_date_time.date }}.txt
        force_basic_auth: yes
#        register: current_config

 #   - name: write config to local file
#      local_action: copy content={{ current_config.content }} dest=/backup/soc/{{ inventory_hostname }}_{{ ansible_date_time.date }}.txt
