---
- name: BACKUP FORTINET CONFIGURATIONS
  hosts: localhost
#  hosts: all
#  connection: local
  gather_facts: false

  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

  tasks:
    - name: BACKUP THE CONFIG
      cli_command:
        command: show full-configuration
#          - show full-configuration
      register: config

    - name: RENAME BACKUP
      copy:
#        src: "{{config_output.backup_path}}"
        content: "{{config.stdout[0]}}"
        dest: "/backup/soc/{{inventory_hostname}}_{{date}}.txt"
